config/routes.rb
Mdh::Application.routes.draw do
  scope module: "sessions" do
    match :new, as: :login, via: [:get], path: "/login"
    match :create, via: [:post], path: "/login"
    match :destroy, as: :logout, via: [:get], path: "/logout"
    match :unauthorized, as: :unauthorized, via: [:get], path: "/unauthorized"
    match :confirm_account, as: :confirm_account, via: [:get], path: "/confirm_account/:auth_token"
  end

  namespace :admin do
    if Rails.env.development?
      mount MailPreview => 'mail_view'
    end

    resources :articles do
      resources :images, only: [:destroy]
      resources :icons, only: [:destroy]
      resources :comments, only: [:destroy]
      collection do
        match "taggings/search", to: "articles#tag_search", as: :tag_search
        match :calendar, via: [:get]
        match :tags, via: [:get]
        match "tags/:tag", to: "articles#tags", via: [:get], as: :tag
        match "permalinker", to: "articles#permalinker", via: [:post]
      end
    end
    resources :users
    root to: 'articles#index'
  end

  scope module: "password_resets" do
    match :new, via: [:get], as: :new_password_reset, path: "/reset/password/new"
    match :edit, via: [:get], as: :edit_password_reset, path: "/reset/password/:id/edit"
    match :create, via: [:post], as: :password_resets, path: "/reset/password"
    match :update, via: [:put], as: :password_reset, path: "/reset/password/:id"
  end

  scope module: "users" do
    match :new, via: [:get], as: :register, path: "/register"
  end
  resources :users, only: [:create, :destroy]

  scope module: "users/confirm" do
    match :create, via: [:post], as: :confirm_create, path: "/confirm"
  end
  resources :confirm, only: [:edit, :update], to: "users/confirm"

  resource :my, only: [:dashboard, :comments], to: "my" do
    match :comments, via: [:get]
    match :dashboard, via: [:get]
    resource :profile, only: [] do
      match :edit, via: [:get], to: "users#edit"
      match :update, via: [:put], to: "users#update"
    end
  end

  resources :articles, only: [:index, :show] do
    resources :comments, except: [:index, :show, :destroy] do
      member do
        match :reply, to: "comments#new_reply", via: [:get]
        match :reply, to: "comments#reply", via: [:post]
      end
    end
    collection do
      match "taggings/search", to: "articles#tag_search", as: :tag_search
      match :calendar, via: [:get]
      match :tags, via: [:get], as: :tags
      match "tags/:tag", to: "articles#tags", via: [:get], as: :tag
      match :typeahead_search, via: [:get]
    end
  end

  root to: 'articles#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :images, as: :assetable, class_name: "Image", dependent: :destroy
  has_one :icon, as: :assetable, class_name: "Icon", dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true, reject_if: proc { |image| image[:attachment].blank? }
  accepts_nested_attributes_for :icon, allow_destroy: true, reject_if: proc { |icon| icon[:attachment].blank? }

  attr_accessor :publish

  acts_as_taggable

  validates :title, presence: true
  validates :content, presence: true
  validates :excerpt, presence: true
  validates :permalink, presence: true, uniqueness: { case_sensitive: false }

  before_validation :set_published_at
  before_create :parameterize_permalink

  scope :draft, where(Article.arel_table[:published_at].eq(nil))
  scope :published, where(Article.arel_table[:published_at].not_eq(nil))
  default_scope order("published_at DESC")

  paginates_per 10

  def self.permalinker(query)
    query.parameterize.presence || "Invalid"
  end

  def self.typeahead_search(query)
    where(arel_table[:title].matches("%#{query}%"))
  end

  def self.to_pretty_json
    scoped.map { |thing| thing.to_pretty_json }
  end

  def to_pretty_json
    {
      title: title,
      published_at: I18n.l(published_at, format: :short),
      permalink: permalink,
    }
  end

  def to_param
    permalink
  end

  def pretty_tag_list(options={})
    # TODO: make it be able to pass in admin
    # also write tests for me
    result = ""
    result << "<ul class='breadcrumb tag-list'>"
    result << ""
    tag_list.each do |tag|
      result << "<li>"
      result << ActionController::Base.helpers.link_to(tag, Rails.application.routes.url_helpers.tag_articles_path(tag))
      result << "<span class='divider'>/</span>" unless tag == tag_list.last
      result << "</li>"
    end
    result << "</ul>"
    result
  end

  def generate_open_graph_meta_tags
    result = ""
    if icon.present?
      result << "<meta property='og:image' content='#{Rails.application.routes.url_helpers.root_url(host: Rails.application.config.super_cool_mailer_host).gsub(/\/$/, '')}#{icon.url(:thumb)}'/>"
    else
      result << "<meta property='og:image' content='#{Rails.application.routes.url_helpers.root_url(host: Rails.application.config.super_cool_mailer_host)}images/favicon.png'/>"
    end
    result << "<meta property='og:title' content=#{title.inspect}/>"
    result << "<meta property='og:description' content=#{pretty_excerpt}/>"
    result << "<meta property='og:url' content='#{Rails.application.routes.url_helpers.article_url(to_param, host:  Rails.application.config.super_cool_mailer_host)}'/>"

    result
  end

  def pretty_excerpt
    result = excerpt.gsub(/\[(\w+)\]\(([^\)]+)\)/, '\1')
    result.inspect
  end

  private

  def set_published_at
    if publish == "1"
      self.update_attribute(:published_at, Time.zone.now)
    end
  end

  def parameterize_permalink
    self.permalink = self.permalink.parameterize if permalink.present?
  end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController
  respond_to :html, :js

  load_and_authorize_resource only: [:index, :new], find_by: :permalink
  load_resource only: [:show, :calendar], find_by: :permalink
  load_resource only: [:edit, :update, :destroy], through: :current_user, find_by: :permalink
  authorize_resource only: [:create, :edit, :update, :destroy, :show]

  def calendar
    authorize! :calendar, Article
    @articles = @articles.published
    @articles_by_date = @articles.group_by { |article| article.published_at.to_date }
    @date = params[:date] ? Date.parse(params[:date]) : Time.zone.now.to_date
  end

  def index
    handle_published
    @articles = @articles.basic_search(params[:query]) if params[:query].present?
    @articles = @articles.page(params[:page]).per(params[:per_page])
  end

  def show
    @root_comments = @article.comments.includes(:user).roots
  end

  def new
    @article.build_icon
  end

  def edit
    @article.build_icon if @article.icon.blank?
  end

  def create
    @article = current_user.articles.new(safe_params)

    if @article.save
      redirect_to admin_article_url(@article), notice: t('admin.articles.controller.create.success')
    else
      flash[:error] = t('admin.articles.controller.create.failure')
      render :new
    end
  end

  def update
    if @article.update_attributes(safe_params)
      redirect_to admin_article_url(@article), notice: t('admin.articles.controller.update.success')
    else
      flash[:error] =  t('admin.articles.controller.update.failure')
      render :edit
    end
  end

  def destroy
    if @article.destroy
      flash[:notice] = t('admin.articles.controller.destroy.success')
    else
      flash[:notice] = t('admin.articles.controller.destroy.failure')
    end

    # do stuff depending on the request type
    respond_to do |format|
      format.html { redirect_to admin_articles_url }
      format.js
    end
  end

  def tags
    authorize! :tag_search, Article
    @articles_tag_counts = Article.tag_counts
    unless params[:tag].blank?
      @articles = Article.tagged_with(params[:tag])
      @articles = @articles.basic_search(params[:query]) if params[:query].present?
      @articles = @articles.page(params[:page]).per(params[:per_page])
    else
      redirect_to root_url
    end
  end

  def tag_search
    authorize! :tag_search, Article
    if params[:query].present?
      @tags = ActsAsTaggableOn::Tag.tag_search(params[:query])
      @tags = @tags.page(params[:page]).per(params[:per_page])
    end
  end

  def permalinker
    render json: Article.permalinker(params[:query])
  end

  private

  def handle_published
    if params[:published].present?
      case params[:published]
      when 'true'
        @articles = @articles.published
      when 'false'
        @articles = @articles.draft
      end
    end
  end

  def safe_params
    safe_attributes = [
      :content,
      :excerpt,
      :permalink,
      :publish,
      :published_at,
      :title,
      :tag_list,
      icon_attributes:
      [
        :attachment,
        :filename
      ],
      images_attributes:
      [
        :attachment,
        :filename
      ]
    ]
    params.require(:article).permit(*safe_attributes)
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_filter :authorize
  load_and_authorize_resource only: [:index, :show], find_by: :permalink
  load_resource only: [:calendar]
  respond_to :html, :js, :json


  def calendar
    authorize! :calendar, Article
    @articles = @articles.published
    @articles_by_date = @articles.group_by { |article| article.published_at.to_date }
    @date = params[:date] ? Date.parse(params[:date]) : Time.zone.now.to_date
  end

  def index
    @articles = @articles.basic_search(params[:query]) if params[:query].present?
    @articles = @articles.page(params[:page]).per(params[:per_page])
  end

  def show
    @root_comments = @article.comments.includes(:user).roots
  end

  def tags
    authorize! :tag_search, Article
    @articles_tag_counts = Article.published.tag_counts
    unless params[:tag].blank?
      @articles = Article.published.tagged_with(params[:tag])
      @articles = @articles.basic_search(params[:query]) if params[:query].present?
      @articles = @articles.page(params[:page]).per(params[:per_page])
    else
      redirect_to root_url
    end
  end

  def tag_search
    authorize! :tag_search, Article
    if params[:query].present?
      @tags = ActsAsTaggableOn::Tag.tag_search(params[:query])
      @tags = @tags.page(params[:page]).per(params[:per_page])
    end
  end

  def typeahead_search
    @articles = Article.published.typeahead_search(params[:query])
    render json: @articles.to_pretty_json
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
  def muted(resource, column, options={})
    if resource.try(column).blank?
      "muted"
    end
  end

  def active(param_name, param_value, options={})

    # We're checking to make sure that parameter is NOT present
    if options[:missing].present?
      return 'active' unless params[param_name].present?
    end

    # Is the parameter present and equal to what I want
    if params[param_name].present? && params[param_name] == param_value
      return 'active'
    end

    # nothing for you
    nil
  end

  def article_per_page_options
    [["10 per page", '10'], ["25 per page", '25'], ["50 per page", '50'], ["100 per page", '100']]
  end
end

app/views/admin/articles/_article.html.haml
%div.media{ class: "#{muted(article, :published_at)} #{current_cycle}", id: "article_#{article.permalink}" }
  = link_to '#', class: "pull-left" do
    - if article.icon.present?
      = image_tag article.icon.url(:thumb), class: 'media-object'
    - else
      = image_tag "pfp_logo_icon.jpg", class: 'media-object'
  %div.media-body
    %h4.media-heading
      = link_to article.title, admin_article_path(article), class: muted(article, :published_at)
      %div.comments_count.inline
        %i.icon-comment
        %span.inline-block= pluralize article.comments.size, 'comment'
      %button.close &times;
    %div
      %code.author= article.try(:user).try(:name)
      - if article.published_at?
        %section.inline.published_at= l(article.published_at, format: :short)
      - if article.updated_at?
        %section.inline.updated_at= l(article.updated_at, format: :short)
      = to_markdown(article.excerpt)
    - if can? :manage, article
      .btn-group.dropup
        = link_to edit_admin_article_path(article), class: "btn" do
          %i.icon-edit
          = t('.edit', default: t("helpers.links.edit"))
        %a.btn.dropdown-toggle{ :"data-toggle" => "dropdown" }
          %span.caret
        %ul.dropdown-menu
          - if can? :update, article
            - if article.published_at.present?
              %li
                = link_to admin_article_path(article, article: { published_at: nil }), method: :put do
                  %i.icon-remove-circle
                  = t(".unpublish")
            - else
              %li
                = link_to admin_article_path(article, article: { publish: "1" }), method: :put do
                  %i.icon-ok-sign
                  = t('.publish')
          - if can? :destroy, article
            %li
              = link_to admin_article_path(article), method: "delete", data: { remote: true, confirm: t('.confirm', default: t("helpers.links.confirm")) } do
                %i.icon-remove
                = t('.destroy', default: t("helpers.links.destroy"))
    - unless article.tag_list.blank?
      %ul.breadcrumb.tag-list
        - article.tag_list.each do |tag|
          %li
            = link_to tag, tag_admin_articles_path(tag), class: muted(article, :published_at)
            - unless tag == article.tag_list.last
              %span.divider /

app/views/admin/articles/_form.html.haml
= simple_form_for [:admin, @article], html: { class: 'form-horizontal', multipart: true } do |f|
  = f.input :title


  = f.input :permalink do
    = f.input_field :permalink
    %span
      = link_to '#', class: 'btn btn-success', id: 'automagic_permalink', title: t(".automagic_permalink"), rel: 'tooltip', data: { placement: 'right' } do
        %i.icon-star.icon-white
        %span.addon
  = f.input :excerpt, as: :text, input_html: { rows: 10, class: "span9" }
  = f.input :content, as: :text, input_html: { rows: 25, class: "span9" }
  = f.input :tag_list, hint: t('.tag_list_hint')
  = f.simple_fields_for :icon do |icon_builder|
    = icon_builder.input :attachment, as: :file, label: t(".icon")
  - if @article.try(:icon).present? && @article.try(:icon).persisted?
    - @article.try(:icon).tap do |icon|
      .control-group{ id: "icon_#{icon.id}" }
        .control-label= t(".icon")
        .controls
          = link_to "#", data: { target: '#', placement: "right", title: icon.pretty_filename, content: icon.url }, class: "pop" do
            = image_tag icon.url(:thumb), class: 'img-polaroid'
          %div= link_to t(".delete_icon"), admin_article_icon_path(icon.assetable.to_param, icon), remote: true, method: :delete, confirm: t(".confirm_delete_icon")
  - @article.images.each do |image|
    .control-group{ id: "image_#{image.id}" }
      .control-label= t(".images")
      .controls
        = link_to "#", data: { target: '#', placement: "right", title: image.pretty_filename, content: image.url }, class: "pop" do
          = image_tag image.url(:thumb), class: 'img-polaroid'
        %div= link_to t(".delete_image"), admin_article_image_path(image.assetable.to_param, image), remote: true, method: :delete, confirm: t(".confirm_delete_image")
  .control-group
    .control-label
    .controls= link_to_add_fields t(".add_image"), f, :images
  .form-actions
    - if can?([:create, :update], @article)
      = f.button :submit, class: 'btn-primary'
    - if can?(:index, @article)
      = link_to t('.cancel', default: t("helpers.links.cancel")), articles_path, class: 'btn'

app/views/admin/articles/_image_fields.html.haml
= f.input :attachment

app/views/admin/articles/calendar.html.haml
- title t('.title')
.page-header
  %div
    %h3.inline= t '.title'
    .calendar-widget.inline
      = link_to admin_articles_path, rel: 'tooltip', title: t('.list_view') do
        %i.icon-list
        = t(".list")

- if current_user
  - content_for(:sidebar) do
    - if can? :create, Article
      = link_to new_admin_article_path, class: "btn btn-success btn-small btn-block" do
        %i.icon-list-alt.icon-white
        %span.addon= t('.new', default: t('helpers.links.new'))
    = link_to dashboard_my_path, class: "btn btn-small btn-block" do
      %i.icon-home
      %span.addon= t("my.my_dashboard")
    - if can? :edit, current_user
      = link_to edit_my_profile_path, class: "btn btn-small btn-block" do
        %i.icon-user
        %span.addon= t("my.my_profile")

%div#articles
  %h2#month
    %div= @date.strftime("%B %Y")
    = link_to "<", date: @date.prev_month
    = form_tag nil, method: :get, id: 'calendar-datepicker', class: 'inline' do
      = text_field_tag :date, @date, class: 'datepicker'
    = link_to ">", date: @date.next_month
  = calendar @date do |date|
    = date.day
    - if @articles_by_date[date]
      %ul
      - @articles_by_date[date].each do |article|
        %li
          = link_to article, data: { remote: true, toggle: "modal", target: "#articleCalendarModal" } do
            = article.title

= render "articles/calendar_modal"

app/views/admin/articles/destroy.js.erb
<% if @article.destroyed? %>
  $("div.media#article_<%= @article.permalink %>").removeWithFlair();
<% end %>
$(".bootstrap-flash").html('<%= j render("shared/flash_messages") %>');

app/views/admin/articles/edit.html.haml
- title t '.title', article_title: @article.title
.page-header
  %h3=t '.title', article_title: @article.title
= render "form"

app/views/admin/articles/index.html.haml
- title t('.title')
.page-header
  %div
    %h3.inline= t '.title'
    .calendar-widget.inline
      = link_to calendar_admin_articles_path, rel: 'tooltip', title: t('.calendar_view') do
        %i.icon-calendar
        = t(".calendar")

= render 'articles/search', placeholder: t(".search_articles")

- content_for :kaminari_per_page do
  = form_tag nil, class: "inline", method: :get do
    = select_tag :per_page, options_for_select(article_per_page_options, selected: params[:per_page]), id: "article_per_page"
- if params[:per_page] && (params[:per_page].to_i >= @articles.total_count)
  %div
    = form_tag nil, class: "inline", method: :get do
      = select_tag :per_page, options_for_select(article_per_page_options, selected: params[:per_page]), id: "article_per_page"

- content_for(:sidebar) do
  - if can? :create, Article
    = link_to new_admin_article_path, class: "btn btn-success btn-small btn-block" do
      %i.icon-list-alt.icon-white
      %span.addon= t('.new', default: t('helpers.links.new'))
    = link_to dashboard_my_path, class: "btn btn-small btn-block btn-inverse" do
      %i.icon-home.icon-white
      %span.addon= t("my.my_dashboard")
    - if can? :edit, current_user
      = link_to edit_my_profile_path, class: "btn btn-small btn-block btn-inverse" do
        %i.icon-user.icon-white
        %span.addon= t("my.my_profile")

#admin_article_controls.btn-toolbar
  .btn-group
    = link_to t(".show_all"), params.merge(published: nil), class: "btn #{active(:published, nil, {missing: :true})}"
    = link_to t(".show_published"), params.merge(published: :true), class: "btn #{active(:published, 'true')}"
    = link_to t(".show_drafts"), params.merge(published: :false), class: "btn #{active(:published, 'false')}"

= paginate @articles

- @articles.each do |article|
  - current_cycle = cycle("odd", "even")
  = render article, current_cycle: current_cycle

= paginate @articles

app/views/admin/articles/show.html.haml
- title t '.title', article_title: @article.title
.page-header
  %h3=t '.title', article_title: @article.title

- content_for(:sidebar) do
  - if can? :edit, @article
    = link_to edit_admin_article_path(@article), class: 'btn btn-warning btn-small btn-block' do
      %i.icon-edit.icon-white
      %span.addon= t('.edit', default: t("helpers.links.edit"))
  - if can? :update, @article
    - if @article.published_at.present?
      = link_to admin_article_path(@article, article: { published_at: nil }), method: :put, class: "btn btn-inverse btn-block" do
        %i.icon-remove-circle.icon-white
        %span.addon= t(".unpublish")
    - else
      = link_to admin_article_path(@article, article: { publish: "1" }), method: :put, class: "btn btn-inverse btn-block" do
        %i.icon-ok-sign.icon-white
        %span.addon= t('.publish')
  - if can? :destroy, @article
    = link_to admin_article_path(@article), method: "delete", data: { confirm: t('.confirm', default: t("helpers.links.confirm")) }, class: 'btn btn-danger btn-small btn-block' do
      %i.icon-remove.icon-white
      %span.addon= t('.destroy', default: t("helpers.links.destroy"))

%div.media
  = link_to @article, class: "pull-left" do
    - if @article.icon.present?
      = image_tag @article.icon.url(:thumb), class: 'media-object'
    - else
      = image_tag "pfp_logo_icon.jpg", class: 'media-object'
  %div.media-body
    %h4.media-heading
      = link_to @article.title, admin_articles_path
    %div
      %code.author= @article.try(:user).try(:name)
      - if @article.published_at?
        %section.inline.published_at= l(@article.published_at, format: :short)
      - if @article.updated_at?
        %section.inline.updated_at= l(@article.updated_at, format: :short) if @article.updated_at?
    - unless @article.tag_list.blank?
      %ul.breadcrumb.tag-list
        - @article.tag_list.each do |tag|
          %li
            = link_to tag, tag_admin_articles_path(tag)
            - unless tag == @article.tag_list.last
              %span.divider /
  .row-fluid
    .lead= to_markdown(@article.excerpt)
  .row-fluid
    .clearfix= to_markdown(@article.content)

  %fieldset
    %legend
      %i.icon-comment
      %span.inline#article_comments_legend= pluralize(@article.comments.size, 'comment').titleize
    %div
      - if current_user
        - if can? :create, Comment
          %p= t(".leave_comments")
          = link_to t(".add_comment"), new_article_comment_path(@article), id: 'new_comment_link', remote: true
      - else
        %p= t(".login_or_register")
    #comments
      - @root_comments.each do |comment|
        = render "comments/comment", comment: comment

app/views/admin/articles/tag_search.html.haml
- title t '.title'
.page-header
  %h3= t '.title'

.row-fluid
  = form_tag nil, method: :get, class: 'form-search' do
    .control-group
    .controls
      = text_field_tag :query, params[:query], placeholder: t(".search_taggings"), class: 'input-medium search-query'
      = submit_tag t(".search"), class: 'btn btn-success'

- if @tags.present?
  = paginate @tags

  %table.table.table-striped
    %thead
      %tr
        %th Tag Name
        %th Occurences
    %tbody
    - @tags.each do |tag|
      %tr
        %td= link_to tag.name, tag_admin_articles_path(tag.name)
        %td= tag.total_taggings_count

app/views/admin/articles/tags.html.haml
- title t '.title', tag: params[:tag].inspect
.page-header
  %h3= t '.title', tag: params[:tag].inspect

.row-fluid
  = form_tag nil, method: :get, class: 'form-search' do
    .control-group
    .controls
      = text_field_tag :query, params[:query], placeholder: t(".search_articles"), class: 'input-medium search-query'
      = submit_tag t(".search"), class: 'btn btn-success'

= paginate @articles

%table.table.table-striped
  - @articles.each do |article|
    = render article

= paginate @articles

- content_for(:sidebar) do
  - if can? :tag_search, Article
    = link_to tag_search_admin_articles_path, class: 'btn btn-success btn-small btn-block' do
      %i.icon-tag.icon-white
      %span.add-on= t(".tag_search")
  - if can? :tag_search, Article
    = link_to "#", data: { toggle: "modal", target: "#articleTagCloudModal" }, class: "btn btn-primary btn-small btn-block" do
      %i.icon-tags.icon-white
      %span.add-on= t('.view_tag_cloud')
  = link_to "#", data: { placement: "left", title: t(".tag_cloud_pop_title"), content: t(".tag_cloud_pop_content") }, class: "pop btn btn-info btn-small btn-block" do
    %i.icon-question-sign.icon-white
    %span.add-on= t(".explain_tag_cloud")

= render "articles/modal"