config/routes.rb
Mdh::Application.routes.draw do
  scope module: "sessions" do
    match :new, as: :login, via: [:get], path: "/login"
    match :create, via: [:post], path: "/login"
    match :destroy, as: :logout, via: [:get], path: "/logout"
    match :unauthorized, as: :unauthorized, via: [:get], path: "/unauthorized"
    match :confirm_account, as: :confirm_account, via: [:get], path: "/confirm_account/:auth_token"
  end

  namespace :admin do
    if Rails.env.development?
      mount MailPreview => 'mail_view'
    end

    resources :articles do
      resources :images, only: [:destroy]
      resources :icons, only: [:destroy]
      resources :comments, only: [:destroy]
      collection do
        match "taggings/search", to: "articles#tag_search", as: :tag_search
        match :calendar, via: [:get]
        match :tags, via: [:get]
        match "tags/:tag", to: "articles#tags", via: [:get], as: :tag
        match "permalinker", to: "articles#permalinker", via: [:post]
      end
    end
    resources :users
    root to: 'articles#index'
  end

  scope module: "password_resets" do
    match :new, via: [:get], as: :new_password_reset, path: "/reset/password/new"
    match :edit, via: [:get], as: :edit_password_reset, path: "/reset/password/:id/edit"
    match :create, via: [:post], as: :password_resets, path: "/reset/password"
    match :update, via: [:put], as: :password_reset, path: "/reset/password/:id"
  end

  scope module: "users" do
    match :new, via: [:get], as: :register, path: "/register"
  end
  resources :users, only: [:create, :destroy]

  scope module: "users/confirm" do
    match :create, via: [:post], as: :confirm_create, path: "/confirm"
  end
  resources :confirm, only: [:edit, :update], to: "users/confirm"

  resource :my, only: [:dashboard, :comments], to: "my" do
    match :comments, via: [:get]
    match :dashboard, via: [:get]
    resource :profile, only: [] do
      match :edit, via: [:get], to: "users#edit"
      match :update, via: [:put], to: "users#update"
    end
  end

  resources :articles, only: [:index, :show] do
    resources :comments, except: [:index, :show, :destroy] do
      member do
        match :reply, to: "comments#new_reply", via: [:get]
        match :reply, to: "comments#reply", via: [:post]
      end
    end
    collection do
      match "taggings/search", to: "articles#tag_search", as: :tag_search
      match :calendar, via: [:get]
      match :tags, via: [:get], as: :tags
      match "tags/:tag", to: "articles#tags", via: [:get], as: :tag
      match :typeahead_search, via: [:get]
    end
  end

  root to: 'articles#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :images, as: :assetable, class_name: "Image", dependent: :destroy
  has_one :icon, as: :assetable, class_name: "Icon", dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true, reject_if: proc { |image| image[:attachment].blank? }
  accepts_nested_attributes_for :icon, allow_destroy: true, reject_if: proc { |icon| icon[:attachment].blank? }

  attr_accessor :publish

  acts_as_taggable

  validates :title, presence: true
  validates :content, presence: true
  validates :excerpt, presence: true
  validates :permalink, presence: true, uniqueness: { case_sensitive: false }

  before_validation :set_published_at
  before_create :parameterize_permalink

  scope :draft, where(Article.arel_table[:published_at].eq(nil))
  scope :published, where(Article.arel_table[:published_at].not_eq(nil))
  default_scope order("published_at DESC")

  paginates_per 10

  def self.permalinker(query)
    query.parameterize.presence || "Invalid"
  end

  def self.typeahead_search(query)
    where(arel_table[:title].matches("%#{query}%"))
  end

  def self.to_pretty_json
    scoped.map { |thing| thing.to_pretty_json }
  end

  def to_pretty_json
    {
      title: title,
      published_at: I18n.l(published_at, format: :short),
      permalink: permalink,
    }
  end

  def to_param
    permalink
  end

  def pretty_tag_list(options={})
    # TODO: make it be able to pass in admin
    # also write tests for me
    result = ""
    result << "<ul class='breadcrumb tag-list'>"
    result << ""
    tag_list.each do |tag|
      result << "<li>"
      result << ActionController::Base.helpers.link_to(tag, Rails.application.routes.url_helpers.tag_articles_path(tag))
      result << "<span class='divider'>/</span>" unless tag == tag_list.last
      result << "</li>"
    end
    result << "</ul>"
    result
  end

  def generate_open_graph_meta_tags
    result = ""
    if icon.present?
      result << "<meta property='og:image' content='#{Rails.application.routes.url_helpers.root_url(host: Rails.application.config.super_cool_mailer_host).gsub(/\/$/, '')}#{icon.url(:thumb)}'/>"
    else
      result << "<meta property='og:image' content='#{Rails.application.routes.url_helpers.root_url(host: Rails.application.config.super_cool_mailer_host)}images/favicon.png'/>"
    end
    result << "<meta property='og:title' content=#{title.inspect}/>"
    result << "<meta property='og:description' content=#{pretty_excerpt}/>"
    result << "<meta property='og:url' content='#{Rails.application.routes.url_helpers.article_url(to_param, host:  Rails.application.config.super_cool_mailer_host)}'/>"

    result
  end

  def pretty_excerpt
    result = excerpt.gsub(/\[(\w+)\]\(([^\)]+)\)/, '\1')
    result.inspect
  end

  private

  def set_published_at
    if publish == "1"
      self.update_attribute(:published_at, Time.zone.now)
    end
  end

  def parameterize_permalink
    self.permalink = self.permalink.parameterize if permalink.present?
  end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController
  respond_to :html, :js

  load_and_authorize_resource only: [:index, :new], find_by: :permalink
  load_resource only: [:show, :calendar], find_by: :permalink
  load_resource only: [:edit, :update, :destroy], through: :current_user, find_by: :permalink
  authorize_resource only: [:create, :edit, :update, :destroy, :show]

  def calendar
    authorize! :calendar, Article
    @articles = @articles.published
    @articles_by_date = @articles.group_by { |article| article.published_at.to_date }
    @date = params[:date] ? Date.parse(params[:date]) : Time.zone.now.to_date
  end

  def index
    handle_published
    @articles = @articles.basic_search(params[:query]) if params[:query].present?
    @articles = @articles.page(params[:page]).per(params[:per_page])
  end

  def show
    @root_comments = @article.comments.includes(:user).roots
  end

  def new
    @article.build_icon
  end

  def edit
    @article.build_icon if @article.icon.blank?
  end

  def create
    @article = current_user.articles.new(safe_params)

    if @article.save
      redirect_to admin_article_url(@article), notice: t('admin.articles.controller.create.success')
    else
      flash[:error] = t('admin.articles.controller.create.failure')
      render :new
    end
  end

  def update
    if @article.update_attributes(safe_params)
      redirect_to admin_article_url(@article), notice: t('admin.articles.controller.update.success')
    else
      flash[:error] =  t('admin.articles.controller.update.failure')
      render :edit
    end
  end

  def destroy
    if @article.destroy
      flash[:notice] = t('admin.articles.controller.destroy.success')
    else
      flash[:notice] = t('admin.articles.controller.destroy.failure')
    end

    # do stuff depending on the request type
    respond_to do |format|
      format.html { redirect_to admin_articles_url }
      format.js
    end
  end

  def tags
    authorize! :tag_search, Article
    @articles_tag_counts = Article.tag_counts
    unless params[:tag].blank?
      @articles = Article.tagged_with(params[:tag])
      @articles = @articles.basic_search(params[:query]) if params[:query].present?
      @articles = @articles.page(params[:page]).per(params[:per_page])
    else
      redirect_to root_url
    end
  end

  def tag_search
    authorize! :tag_search, Article
    if params[:query].present?
      @tags = ActsAsTaggableOn::Tag.tag_search(params[:query])
      @tags = @tags.page(params[:page]).per(params[:per_page])
    end
  end

  def permalinker
    render json: Article.permalinker(params[:query])
  end

  private

  def handle_published
    if params[:published].present?
      case params[:published]
      when 'true'
        @articles = @articles.published
      when 'false'
        @articles = @articles.draft
      end
    end
  end

  def safe_params
    safe_attributes = [
      :content,
      :excerpt,
      :permalink,
      :publish,
      :published_at,
      :title,
      :tag_list,
      icon_attributes:
      [
        :attachment,
        :filename
      ],
      images_attributes:
      [
        :attachment,
        :filename
      ]
    ]
    params.require(:article).permit(*safe_attributes)
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_filter :authorize
  load_and_authorize_resource only: [:index, :show], find_by: :permalink
  load_resource only: [:calendar]
  respond_to :html, :js, :json


  def calendar
    authorize! :calendar, Article
    @articles = @articles.published
    @articles_by_date = @articles.group_by { |article| article.published_at.to_date }
    @date = params[:date] ? Date.parse(params[:date]) : Time.zone.now.to_date
  end

  def index
    @articles = @articles.basic_search(params[:query]) if params[:query].present?
    @articles = @articles.page(params[:page]).per(params[:per_page])
  end

  def show
    @root_comments = @article.comments.includes(:user).roots
  end

  def tags
    authorize! :tag_search, Article
    @articles_tag_counts = Article.published.tag_counts
    unless params[:tag].blank?
      @articles = Article.published.tagged_with(params[:tag])
      @articles = @articles.basic_search(params[:query]) if params[:query].present?
      @articles = @articles.page(params[:page]).per(params[:per_page])
    else
      redirect_to root_url
    end
  end

  def tag_search
    authorize! :tag_search, Article
    if params[:query].present?
      @tags = ActsAsTaggableOn::Tag.tag_search(params[:query])
      @tags = @tags.page(params[:page]).per(params[:per_page])
    end
  end

  def typeahead_search
    @articles = Article.published.typeahead_search(params[:query])
    render json: @articles.to_pretty_json
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
  def muted(resource, column, options={})
    if resource.try(column).blank?
      "muted"
    end
  end

  def active(param_name, param_value, options={})

    # We're checking to make sure that parameter is NOT present
    if options[:missing].present?
      return 'active' unless params[param_name].present?
    end

    # Is the parameter present and equal to what I want
    if params[param_name].present? && params[param_name] == param_value
      return 'active'
    end

    # nothing for you
    nil
  end

  def article_per_page_options
    [["10 per page", '10'], ["25 per page", '25'], ["50 per page", '50'], ["100 per page", '100']]
  end
end

app/views/articles/_article.html.haml
%div.media{ class: "#{muted(article, :published_at)} media-article" }
  = link_to article, class: "pull-left" do
    - if article.icon.present?
      = image_tag article.icon.url(:thumb), class: 'media-object'
    - else
      = image_tag "pfp_logo_icon.jpg", class: 'media-object'
  %div.media-body
    %h4.media-heading
      = link_to article.title, article, class: muted(article, :published_at)
      %div.comments_count.inline
        %i.icon-comment
        %span.inline-block= pluralize article.comments.size, 'comment'
      %button.close &times;
    %div
      %code.author= article.try(:user).try(:name)
      - if article.published_at?
        %section.inline.published_at= l(article.published_at, format: :short)
      - if article.updated_at?
        %section.inline.updated_at= l(article.updated_at, format: :short) if article.updated_at?
      .excerpt= to_markdown(article.excerpt)
    - unless article.tag_list.blank?
      %ul.breadcrumb.tag-list
        - article.tag_list.each do |tag|
          %li
            = link_to tag, tag_articles_path(tag), class: muted(article, :published_at)
            - unless tag == article.tag_list.last
              %span.divider /

app/views/articles/_calendar_modal.html.haml
%div.modal{tabindex: -1, id: "articleCalendarModal", style: "display: none;"}
  .modal-header
    %button.close{ data: { dismiss: "modal" } } &times;
    %h3#article_title ...
  .modal-body
    %h6.weak#tag_list ...
    %div#excerpt ...
  .modal-footer
    %section.inline.published_at
    %section.inline.updated_at

app/views/articles/_modal.html.haml
%div.modal{tabindex: -1, id: "articleTagCloudModal", style: "display: none;"}
  .modal-header
    %button.close{ data: { dismiss: "modal" } } &times;
    %h3= t(".tag_cloud")
    %h6.weak#current_tag= t('.current_tag', tag: params[:tag].inspect )
  .modal-body
    %div#article_tag_cloud
    - tag_cloud @articles_tag_counts, %w[tag_small tag_medium tag_large] do |tag, css_class|
      = link_to tag.name, tag_articles_path(tag.name), class: css_class

app/views/articles/_search.html.haml
.row-fluid
  = form_tag nil, method: :get, class: 'form-search' do
    .control-group
    .controls
      = text_field_tag :query, nil, placeholder: placeholder, class: 'input-medium search-query typeahead', autocomplete: 'off', data: { provide: 'typeahead', source: typeahead_search_articles_path }
      = submit_tag t(".search"), class: 'btn btn-success'

app/views/articles/calendar.html.haml
- title t('.title')
.page-header
  %div
    %h3.inline= t '.title'
    .calendar-widget.inline
      = link_to articles_path, rel: 'tooltip', title: t('.list_view') do
        %i.icon-list
        = t(".list")

- if current_user
  - content_for(:sidebar) do
    = link_to dashboard_my_path, class: "btn btn-small btn-block" do
      %i.icon-home
      %span.addon= t("my.my_dashboard")
    - if can? :edit, current_user
      = link_to edit_my_profile_path, class: "btn btn-small btn-block" do
        %i.icon-user
        %span.addon= t("my.my_profile")

%div#articles
  %h2#month
    %div= @date.strftime("%B %Y")
    = link_to "<", date: @date.prev_month
    = form_tag nil, method: :get, id: 'calendar-datepicker', class: 'inline' do
      = text_field_tag :date, @date, class: 'datepicker'
    = link_to ">", date: @date.next_month
  = calendar @date do |date|
    = date.day
    - if @articles_by_date[date]
      %ul
      - @articles_by_date[date].each do |article|
        %li
          = link_to article, data: { remote: true, toggle: "modal", target: "#articleCalendarModal" } do
            = article.title

= render "calendar_modal"

app/views/articles/index.html.haml
- title t('.title')
.page-header
  %div
    %h3.inline= t '.title'
    .calendar-widget.inline
      = link_to calendar_articles_path, rel: 'tooltip', title: t('.calendar_view') do
        %i.icon-calendar
        = t(".calendar")

= render 'search', placeholder: t(".search_articles")

- content_for :kaminari_per_page do
  = form_tag nil, class: "inline", method: :get do
    = select_tag :per_page, options_for_select(article_per_page_options, selected: params[:per_page]), id: "article_per_page"

- if params[:per_page] && (params[:per_page].to_i >= @articles.total_count)
  %div
    = form_tag nil, class: "inline", method: :get do
      = select_tag :per_page, options_for_select(article_per_page_options, selected: params[:per_page]), id: "article_per_page"

- if current_user
  - content_for(:sidebar) do
    - if can? :manage, :all
      = link_to admin_root_path, class: "btn btn-inverse btn-small btn-block" do
        %i.icon-heart.icon-white
        %span.addon= t(".admin")
    = link_to dashboard_my_path, class: "btn btn-small btn-block" do
      %i.icon-home
      %span.addon= t("my.my_dashboard")
    - if can? :edit, current_user
      = link_to edit_my_profile_path, class: "btn btn-small btn-block" do
        %i.icon-user
        %span.addon= t("my.my_profile")

= paginate @articles

- @articles.each do |article|
  = render article

= paginate @articles

app/views/articles/show.html.haml
- title t '.title', article_title: @article.title
.page-header
  %h3=t '.title', article_title: @article.title

%div.media
  = link_to @article, class: "pull-left" do
    - if @article.icon.present?
      = image_tag @article.icon.url(:thumb), class: 'media-object'
    - else
      = image_tag "pfp_logo_icon.jpg", class: 'media-object'
  %div.media-body
    %h4.media-heading
      = link_to @article.title, articles_path
    %div
      %code.author= @article.try(:user).try(:name)
      - if @article.published_at?
        %section.inline.published_at= l(@article.published_at, format: :short)
      - if @article.updated_at?
        %section.inline.updated_at= l(@article.updated_at, format: :short) if @article.updated_at?
    - unless @article.tag_list.blank?
      %ul.breadcrumb.tag-list
        - @article.tag_list.each do |tag|
          %li
            = link_to tag, tag_articles_path(tag)
            - unless tag == @article.tag_list.last
              %span.divider /
  .row-fluid
    .lead= to_markdown(@article.excerpt)
  .row-fluid
    .clearfix= to_markdown(@article.content)

  %fieldset
    %legend
      %i.icon-comment
      %span.inline#article_comments_legend= pluralize(@article.comments.size, 'comment').titleize
    %div
      - if current_user
        - if can? :create, Comment
          %p= t(".leave_comments")
          = link_to t(".add_comment"), new_article_comment_path(@article), id: 'new_comment_link', remote: true
      - else
        %p= t(".login_or_register")
    #comments
      - if @root_comments.present?
        - @root_comments.each do |root_comment|
          = render "comments/comment", comment: root_comment

app/views/articles/show.js.erb
$('#articleCalendarModal').find('h3#article_title').html("<%= j(link_to @article.title, @article) %>");
$('#articleCalendarModal').find('h6.weak#tag_list').html("<%= j(@article.pretty_tag_list.html_safe) %>");
$('#articleCalendarModal').find('div#excerpt').html("<%= j(to_markdown(@article.excerpt)) %>");
$('#articleCalendarModal').find('section.inline.published_at').html("<%= j(l @article.published_at, format: :short) %>");
$('#articleCalendarModal').find('section.inline.updated_at').html("<%= j(l @article.updated_at, format: :short) %>");

app/views/articles/tag_search.html.haml
- title t '.title'
.page-header
  %h3= t '.title'

.row-fluid
  = form_tag nil, method: :get, class: 'form-search' do
    .control-group
    .controls
      = text_field_tag :query, params[:query], placeholder: t(".search_taggings"), class: 'input-medium search-query'
      = submit_tag t(".search"), class: 'btn btn-success'

- if @tags.present?
  = paginate @tags

  %table.table.table-striped
    %thead
      %tr
        %th Tag Name
        %th Occurences
    %tbody
    - @tags.each do |tag|
      %tr
        %td= link_to tag.name, tag_articles_path(tag.name)
        %td= tag.published_taggings_count

app/views/articles/tags.html.haml
- title t '.title', tag: params[:tag].inspect
.page-header
  %h3= t '.title', tag: params[:tag].inspect

.row-fluid
  = form_tag nil, method: :get, class: 'form-search' do
    .control-group
    .controls
      = text_field_tag :query, params[:query], placeholder: t(".search_articles"), class: 'input-medium search-query'
      = submit_tag t(".search"), class: 'btn btn-success'

= paginate @articles

%table.table.table-striped
  - @articles.each do |article|
    = render article

= paginate @articles

- content_for(:sidebar) do
  - if can? :tag_search, Article
    = link_to tag_search_articles_path, class: 'btn btn-success btn-small btn-block' do
      %i.icon-tag.icon-white
      %span.add-on= t(".tag_search")
  - if can? :tag_search, Article
    = link_to "#", data: { toggle: "modal", target: "#articleTagCloudModal" }, class: "btn btn-primary btn-small btn-block" do
      %i.icon-tags.icon-white
      %span.add-on= t('.view_tag_cloud')
  = link_to "#", data: { placement: "left", title: t(".tag_cloud_pop_title"), content: t(".tag_cloud_pop_content") }, class: "pop btn btn-info btn-small btn-block" do
    %i.icon-question-sign.icon-white
    %span.add-on= t(".explain_tag_cloud")

= render "modal"