config/routes.rb
Mdh::Application.routes.draw do
  scope module: "sessions" do
    match :new, as: :login, via: [:get], path: "/login"
    match :create, via: [:post], path: "/login"
    match :destroy, as: :logout, via: [:get], path: "/logout"
    match :unauthorized, as: :unauthorized, via: [:get], path: "/unauthorized"
    match :confirm_account, as: :confirm_account, via: [:get], path: "/confirm_account/:auth_token"
  end

  namespace :admin do
    if Rails.env.development?
      mount MailPreview => 'mail_view'
    end

    resources :articles do
      resources :images, only: [:destroy]
      resources :icons, only: [:destroy]
      resources :comments, only: [:destroy]
      collection do
        match "taggings/search", to: "articles#tag_search", as: :tag_search
        match :calendar, via: [:get]
        match :tags, via: [:get]
        match "tags/:tag", to: "articles#tags", via: [:get], as: :tag
        match "permalinker", to: "articles#permalinker", via: [:post]
      end
    end
    resources :users
    root to: 'articles#index'
  end

  scope module: "password_resets" do
    match :new, via: [:get], as: :new_password_reset, path: "/reset/password/new"
    match :edit, via: [:get], as: :edit_password_reset, path: "/reset/password/:id/edit"
    match :create, via: [:post], as: :password_resets, path: "/reset/password"
    match :update, via: [:put], as: :password_reset, path: "/reset/password/:id"
  end

  scope module: "users" do
    match :new, via: [:get], as: :register, path: "/register"
  end
  resources :users, only: [:create, :destroy]

  scope module: "users/confirm" do
    match :create, via: [:post], as: :confirm_create, path: "/confirm"
  end
  resources :confirm, only: [:edit, :update], to: "users/confirm"

  resource :my, only: [:dashboard, :comments], to: "my" do
    match :comments, via: [:get]
    match :dashboard, via: [:get]
    resource :profile, only: [] do
      match :edit, via: [:get], to: "users#edit"
      match :update, via: [:put], to: "users#update"
    end
  end

  resources :articles, only: [:index, :show] do
    resources :comments, except: [:index, :show, :destroy] do
      member do
        match :reply, to: "comments#new_reply", via: [:get]
        match :reply, to: "comments#reply", via: [:post]
      end
    end
    collection do
      match "taggings/search", to: "articles#tag_search", as: :tag_search
      match :calendar, via: [:get]
      match :tags, via: [:get], as: :tags
      match "tags/:tag", to: "articles#tags", via: [:get], as: :tag
      match :typeahead_search, via: [:get]
    end
  end

  root to: 'articles#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic

  has_secure_password
  has_gravatar

  has_many :permissions
  has_many :roles, through: :permissions
  has_many :articles

  # Comments that belong to my articles, whether I was the comment author or not
  has_many :comments
  has_many :comments, through: :articles

  # Comments that I made on ANY article
  has_many :my_comments, class_name: 'Comment', foreign_key: :user_id

  validates :password,
    on: :create,
    presence: true
  validates :password_confirmation,
    on: :create,
    presence: true
  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: Rails.application.config.email_regex }

  before_create :generate_auth_token
  before_create :generate_confirm_token
  before_create :default_to_commenter
  after_create :send_confirmation_email

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def name
    "#{first_name.presence} #{last_name.presence}"
  end

  def is?(role_key)
    roles.get(role_key).present?
  end

  def confirmed?
    # confirming the account nils the confirm_token and sets confirmed_at
    confirmed_at.present? && (confirm_token == nil)
  end

  def confirm_account
    self.update_attributes(confirmed_at: Time.zone.now, confirm_token: nil)
  end

  # Not private so we can call it again to resend the confirmation
  def send_confirmation_email
    return false if /\w@(example)\.com/.match(self.email)
    UserMailer.confirmation(self).deliver unless confirmed?
  end

  def send_password_reset_email
    self.generate_password_reset_token
    UserMailer.reset_password(self).deliver unless password_reset_expired?
  end

  def generate_password_reset_token
    generate_token(:password_reset_token)
    save!
  end

  def password_reset_expired?
    # Don't send the email if the token or time is blank
    return true if password_reset_token.blank?
    return true if password_reset_sent_at.blank?

    # Don't send the email if it's been 2 hours since they requested it
    return true if password_reset_sent_at < (Time.zone.now - 2.hours)

    # Don't send to example.com
    return true if /\w@(example)\.com/.match(self.email)
  end

  def destroy_password_reset
    # they used up their password reset request
    self.update_attributes(password_reset_sent_at: nil, password_reset_token: nil)
  end

  private

  def generate_auth_token
    generate_token(:auth_token)
  end

  def generate_confirm_token
    generate_token(:confirm_token)
  end

  def default_to_commenter
    role = Role.find_by_key(:commenter)
    if role && self.roles.empty?
      self.permissions.build(role_id: role.id)
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  load_and_authorize_resource except: [:create]
  authorize_resource only: :create

  respond_to :html, :js

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @user = User.new(safe_params)
    if @user.save
      redirect_to admin_user_url(@user), notice: t('admin.users.controller.create.success')
    else
      flash[:error] = t('admin.users.controller.create.failure')
      render :new
    end
  end

  def update
    if @user.update_attributes(safe_params)
      redirect_to admin_user_url(@user), notice: t('admin.users.controller.update.success')
    else
      flash[:error] =  t('admin.users.controller.update.failure')
      render :edit
    end
  end

  def destroy
    unless @user == current_user
      @user.destroy
      flash[:notice] = t('admin.users.controller.destroy.success')
    else
      flash[:error] = t('admin.users.controller.destroy.prevent_self_destroy')
    end
    redirect_to admin_users_url
  end

  private

  def safe_params
    safe_attributes = [
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation,
      :display_email,
    ]
    if current_user && current_user.is?(:admin)
      safe_attributes += [:role_ids]
    end
    params.require(:user).permit(*safe_attributes)
  end

end

app/controllers/users/confirm_controller.rb
class Users::ConfirmController < ApplicationController
  skip_before_filter :authorize
  before_filter :load_user, except: [:create]
  respond_to :html, :js

  def create
    @user = User.find_by_auth_token!(params[:auth_token])
    if @user.send_confirmation_email
      @result = true
      flash.now[:notice] = t('users.confirm.controller.create.success')
    else
      @result = false
      flash.now[:error] = t('users.confirm.controller.create.failure')
    end
  end

  def edit
    authorize! :confirm, User
  end

  def update
    authorize! :confirm, User
    if @user.confirm_account
      redirect_to login_url, notice: t('users.confirm.controller.update.success')
    else
      flash.now[:error] = t('users.confirm.controller.update.failure')
      render :edit
    end
  end

  private

  def load_user
    @user = User.find_by_confirm_token!(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authorize, only: [:new, :create]
  load_and_authorize_resource except: [:new, :create]
  authorize_resource only: :create
  respond_to :html

  def new
    if current_user
      # don't let them register if they're already logged in
      redirect_to dashboard_my_url, notice: t('users.controller.new.already_logged_in')
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(safe_params)
    if @user.save
      flash[:notice] = t('users.controller.create.success')
      redirect_to login_url
    else
      flash[:error] = t('users.controller.create.failure')
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(safe_params)
      redirect_to dashboard_my_url, notice: t('users.controller.update.success')
    else
      flash[:error] =  t('users.controller.update.failure')
      render :edit
    end
  end

  def destroy
    unless @user == current_user
      @user.destroy
      flash[:notice] = t('users.controller.destroy.success')
    else
      flash[:error] = t('users.controller.destroy.prevent_self_destroy')
    end
    redirect_to users_url
  end

  private

  def safe_params
    safe_attributes = [
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation,
      :display_email,
    ]
    params.require(:user).permit(*safe_attributes)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.haml
= simple_form_for [:admin, @user], html: { class: 'form-horizontal' } do |f|
  = f.input :first_name
  = f.input :last_name
  = f.input :email
  = f.input :display_email, as: :radio_buttons
  = f.input :password
  = f.input :password_confirmation
  - if can? :manage, @user
    = f.input :role_ids, collection: Role.all, as: :check_boxes
  .form-actions
    = f.button :submit, class: 'btn-primary'
    = link_to t('.cancel', default: t("helpers.links.cancel")), admin_users_path, class: 'btn'

app/views/admin/users/_user.html.haml
%tr
  %td= link_to user.last_name, admin_user_path(user)
  %td= user.first_name
  %td= user.email
  %td=l(user.created_at, format: :short)
  %td
    - if can? :edit, user
      = link_to edit_admin_user_path(user), class: 'btn btn-mini btn-warning' do
        %i.icon-edit
        %span.addon= t('.edit', default: t("helpers.links.edit"))
    - if current_user == user
      - if can? :destroy, user
        = link_to "#", disabled: true, class: 'btn btn-mini btn-danger pop', data: { title: t('.delete_user_title'), content: t('.delete_user_content') } do
          %i.icon-remove
          %span.addon= t('.destroy', default: t("helpers.links.destroy"))
    - else
      - if can? :destroy, user
        = link_to admin_user_path(user), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm")) }, id: "user_destroy_#{user.id}", class: 'btn btn-mini btn-danger', id: "user_destroy_#{user.id}" do
          %i.icon-remove
          %span.addon= t('.destroy', default: t("helpers.links.destroy"))

app/views/admin/users/edit.html.haml
- title t '.title', name: @user.name
.page-header
  %h3=t '.title', name: @user.name
= render "form"

app/views/admin/users/index.html.haml
- title t('.title')
.page-header
  %h3=t '.title'

- content_for(:sidebar) do
  - if can? :create, User
    = link_to new_admin_user_path, class: "btn btn-success btn-small btn-block" do
      %i.icon-user.icon-white
      %span.addon= t('.new', default: t("helpers.links.new"))

%table.table.table-striped
  %thead
    %tr
      %th= User.human_attribute_name(:last_name)
      %th= User.human_attribute_name(:first_name)
      %th= User.human_attribute_name(:email)
      %th= User.human_attribute_name(:created_at)
      %th=t '.actions', default: t("helpers.actions")
  %tbody
    - @users.each do |user|
      = render user

app/views/admin/users/new.html.haml
- title t '.title'
.page-header
  %h3=t '.title'
= render "form"

app/views/admin/users/show.html.haml
- title t '.title', name: @user.name
.page-header
  %h3=t '.title', name: @user.name

- content_for(:sidebar) do
  - if can? :edit, @user
    = link_to edit_admin_user_path(@user), class: 'btn btn-warning btn-small btn-block' do
      %i.icon-edit
      %span.addon= t('.edit', default: t("helpers.links.edit"))
  - if current_user == @user
    - if can? :destroy, @user
      = link_to "#", disabled: true, class: 'btn btn-danger btn-small btn-block pop', data: { placement: "left", title: t('.delete_user_title'), content: t('.delete_user_content') } do
        %i.icon-remove
        %span.addon= t('.destroy', default: t("helpers.links.destroy"))
  - else
    - if can? :destroy, @user
      = link_to admin_user_path(@user), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm")) }, class: 'btn btn-danger btn-small btn-block' do
        %i.icon-remove
        %span.addon= t('.destroy', default: t("helpers.links.destroy"))

%p
  %strong= User.human_attribute_name(:first_name) + ':'
  %br
  = @user.first_name
%p
  %strong= User.human_attribute_name(:last_name) + ':'
  %br
  = @user.last_name
%p
  %strong= User.human_attribute_name(:email) + ':'
  %br
  = @user.email
%p
  %strong= User.human_attribute_name(:display_email) + ':'
  %br
  = @user.display_email

- unless @user.roles.blank?
  %dl
    %dt Roles
    - @user.roles.each do |role|
      %dd= role.name